### ISSUE TITLE
Donation target start time

### ISSUE THREAD

**Issue by Floryn** [septor/anteup#16]
The menu progress bar calculates (adds/displays) the ENTIRE received donations, regardless of the years. It should only display the donations made within a  predefined period of time, i.e 01.01.2012-31.12.2012. Otherwise after each due date, when setting a new date you have to increase the original target, so if it said 200 Euro until 31.12.2011, on 01.01.2012 I have to increase the target amount to 400 Euro...now this could prove to be tricky when it says  90% donation received and  on _remaining amount_ will say: €40 Euro instead of 20 Euro.

*My solution:  add a start-end date for the progression bar to look for.*

**Comment by septor** [comment]
This actually should be solved with the latest rewrite, since things are compared by Unix timestamps now instead of whatever weird way I used before.

@Floryn if you ever use the v2 version of this in the future and it's not working as intended, feel free to reopen this!
