### ISSUE TITLE
weird values for preferencies

### ISSUE THREAD

**Issue by Jimmi08** [septor/anteup#29]
At first, thank you for this plugin.  I noticed this:
Some preferencies have no translated strings, but their values are weird (you have different variables in config file) 
- fresh install of e107 latest github
- latest anteup plugin
![image](https://cloud.githubusercontent.com/assets/5429548/11219184/664afb3a-8d59-11e5-9085-3ba2ecb6f166.png)

 
And some suggestions:
- maybe you could add sitelink when install plugin
- when you create donation in admin, date should be mandatory or at least to fill actual time (otherwise there is zero value)

**Comment by septor** [comment]
Which values are weird? The LAN calls are the default text. You can change it to whatever you want, but if you don't then it pulls the text from the LAN file.

Agreed on the site link. I didn't even think about that, I'll get that in when I'm on a more reliable connection and can plug my laptop back in.

I should put checks in place I suppose, or make default values. Good call!

**Comment by Jimmi08** [comment]
Oh, sorry, I totally forget to look at plugin.xml file. It's just - when I see not translated strings, it seems to me as error. Now I see how you get this display. Thanks for explanation.

**Comment by septor** [comment]
Not a problem, I'm not sure it's the best way to handle things but it works! Thanks for the feedback though, it's appreciated.

**Comment by Jimmi08** [comment]
I will need to solve this for other plugin and make from it something like - how to do it right way. You don't need to change anything, I just want to write my thoughts:
- I can't leave it empty (and test if empty, use default lang string), because somebody wants no title
- I can't use English text (f.e. Text from lang file, Default text) 
- I don't want to use your solution with LAN_

I consider 2 ways how to do it - to use empty field and next checkbox with Leave it empty (but with admin UI there will be new line)
- inside install_setup() to create already translated values for these preferencies.

**Comment by septor** [comment]
Well, here's the thing. You can just leave the field blank and if there is no value, use the LAN.

The issue I have with the above on, let's say, the menu text and page text, maybe someone doesn't want to have any text there at all. How would they make it blank? You could use toggles to have it display the contents or not, but meh. That's more preferences to hog up.
