### ISSUE TITLE
Issue: return.php 403 Forbidden + Tracking Donarions

### ISSUE THREAD

**Issue by LaocheXe** [septor/anteup#31]
When donating, after it's all done, return to the site link issue is - 403 Forbidden error, link: e107_plugins/anteup/return.php?thanks

On the site someone donated $25 (paypal took out a dollar or so) and I donated $5 to check if all is well, payment sent to paypal - but doesn't track on the website.

**Comment by LaocheXe** [comment]
Update: all files in the plugin folder are set to 644 - idk if that is a server side issue - change return.php to 755 and works now.

**Comment by septor** [comment]
So changing the permissions of return.php to 255 allows the donations to be logged?

**Comment by LaocheXe** [comment]
No, donations aren't being logged.

Changing the permissions of return.php to 755 allows the user who does donate that gets redirected to that page after the paypal donation is sent - will now show the page - before the perms was 644 and gave a Forbidden 403 error on the page.

**Comment by septor** [comment]
Alright, I'll look into this.

**Comment by Moc** [comment]
Files should be 655, folders/directories should be 755. If you have to put files to 755 in order to work, something is completely wrong and this is usually server side. The Apache error log may provide more information.

**Comment by Moc** [comment]
@LaocheXe I have rewritten lots of things and I think your issues should be resolved. Please update from Github and let me know.
