### ISSUE TITLE
Issue: Plugin Menu Due Date

### ISSUE THREAD

**Issue by LaocheXe** [septor/anteup#35]
Currently the Due Date is showing: 1498190400

http://tf13arma.com/forum

**Comment by septor** [comment]
What does the Last Due date show?

I think someone (me, but I'm blaming @Moc because he's not here to defend himself) forgot to convert the date.

**Comment by Moc** [comment]
Probably me haha. 

@septor: use e107::getDate()->convert_date() 

See my oweme plugin (bit outdated) for an example.

**Comment by Moc** [comment]
Now this is really strange. For me, when I change the date in the AnteUp preferences, it saves it to the database as `Thursday, 02 Jun, 2016` rather than the UNIX datestamp. 

Would this be a bug in e107? Normally, in the admin UI, it should save datestamp fields as the unix datestamp... 

And then the question also is, how did @LaocheXe manage to save it as a unix datestamp on his webiste :smile:

**Comment by LaocheXe** [comment]
@Moc - well very simple..... Something did it for me with out me knowin lol

**Comment by septor** [comment]
It uses the datepicker to get the date, and should be stored however the system stores it.

I've saw incorrect dates displayed, but never unix timestamps.

I say again, how does the Last Due Date display?

**Comment by LaocheXe** [comment]
![capture](https://cloud.githubusercontent.com/assets/5818022/15631322/c5f83ab2-2529-11e6-837d-9f3f74435955.PNG)

**Comment by septor** [comment]
What does it look like in the menu. I would expect it to render correctly in the admin area since it's storing and pulling the same data as any other datepicker field.

**Comment by LaocheXe** [comment]
![capture](https://cloud.githubusercontent.com/assets/5818022/15634867/51454ad2-2594-11e6-8403-1e545d7a4098.PNG)

**Comment by septor** [comment]
Add `{ANTEUP_LASTDUE}` to your template.

**Comment by LaocheXe** [comment]
Still the same

**Comment by Moc** [comment]
Figured it out. I was running an outdated version of e107. When updated with the latest Github files, AnteUp correctly saves a UNIX timestamp. 

Fixes incoming, hold tight! :smile:

**Comment by Moc** [comment]
- Update AnteUp from Github
- Update e107 from Github (to be sure)
- Retest, and let me know if it's fixed :)

**Comment by septor** [comment]
Thanks, Tijn!
