### ISSUE TITLE
Most recent Donators Feature

### ISSUE THREAD

**Issue by mortalites** [septor/anteup#37]
Add 5 Most recent donator names and donation amount to the bottom of the menu.
Also maybe an option to not use the time when the donations are do. I would like to just use the Date.

**Comment by septor** [comment]
For just the date, set the time for midnight and it will be the same as
what you're asking for.

I'll comment on the request later. I haven't coded for e107 in awhile and
just recently had time to start coding things again.

**Comment by Moc** [comment]
> Also maybe an option to not use the time when the donations are do. I would like to just use the Date.

You can now edit the template, to achieve what you want use `{ANTEUP_DONATION_DATE}`. It then uses the format set in the Anteup preferences in the admin section. Default is relative: `{ANTEUP_DONATION_DATE: format=relative}`

**Comment by Moc** [comment]
`{ANTEUP_MOSTRECENT}` now added as a shortcode and added to the default template as well. 
You can specify how many usernames you want to list by doing e.g. `{ANTEUP_MOSTRECENT: amount=10}`
