### ISSUE TITLE
status is ignored

### ISSUE THREAD

**Issue by Jimmi08** [septor/anteup#40]
![image](https://cloud.githubusercontent.com/assets/5429548/21769307/52da7552-d67e-11e6-89c0-ddc08a39c441.png)

- in the progress bar donation is calculated alhought status is pending (the same with denied)
- most recent donators list is empty, tested with completed donation too

**Comment by septor** [comment]
Pending being calculated is an easy fix, since I believe the progress bar just takes the amount donated and doesn't check the status.

Not sure on the donators bit since @Moc coded that part but I'll have a look.
