### ISSUE TITLE
Make sure plugin prefs are stored in v2 format

### ISSUE THREAD

**Issue by Moc** [septor/anteup#47]
New format in v2: plugin preferences are stored in their own row, not in core. 
Migration code to be added in the upgrade routine for next release: http://e107.org/developer-manual/plugin-basics#upgrading-v1-x-plugins

(Some installations may have used AnteUp from v1, which was pretty different)

**Comment by septor** [comment]
I don't see how this is a bug. It functions as it is just fine, it's just not the standard way of doing it. Switching it to enhancement.

**Comment by Norwayman** [comment]
@Moc @septor Well, I lost almost all of my prefs due to using the birthday pluging which appearantly used the core way os storing. SO CaMeRon made a fix for this a few weeks back. So in my opinion it should be done in the new way not to cause problems for people. But, as you both know I am not a programmer and I do not really know the difference.....just my 2 cents worth! :)

**Comment by Moc** [comment]
@septor Sorry, added this past midnight and then my brain just shuts off haha

@Norwayman Yes, if you have installed any version available from this Github page (and these are also the ones that are on e107.org) then you are already using the v2 method of saving prefs. There were a handful of occurences that Cameron notified me off, where people had been using an older version of AnteUp (before the rewrite to v2), in which the plugins were stored the old way. 

You can verify that your preferences are stored correctly in the `Preference editor` (Admin Area > Tools > Database). `AnteUp` should be listed as an option in the dropdown menu. When core is selected, you should NOT see any AnteUp preferences. 

I'll include a migration routine in the next AnteUp release to make sure the preferences are stored correctly for everyone.

**Comment by Norwayman** [comment]
@moc Thanks for guiding me in the right direction. Yes, the AnteUp is listed as an option in the dropdown manu and NOT showing when core is selected. SO I guess I am using the newest method then :)

**Comment by septor** [comment]
Most people will be fine. I don't think many people will have had AnteUp installed on a v1 install of e107 and then upgrade e107 to v2, which would cause this issue (even though you'd have to reinstall AnteUp).
