### ISSUE TITLE
Issue: Date Picker

### ISSUE THREAD

**Issue by LaocheXe** [septor/anteup#52]
While on the front end of a site, on Donations page, the date picker is all white, cant see anything.

![so-white](https://user-images.githubusercontent.com/5818022/27940200-e31b60c6-628e-11e7-8582-8953ac3e0b82.JPG)

Digging into this I notice this element.style not on any .css file

![element-style](https://user-images.githubusercontent.com/5818022/27940211-f6266576-628e-11e7-9057-f08bcbd43655.JPG)

I went in using FireBug and added color: #000; into the element, and it shows:

![element-style-color](https://user-images.githubusercontent.com/5818022/27940226-098bbaee-628f-11e7-9255-c86d766fbeb4.JPG)

Sad part is, adding to the style.css of the theme, it does not show the color. Any ideas on how to get this working?

**Comment by Moc** [comment]
@LaocheXe Is this one still an issue?

**Comment by LaocheXe** [comment]
Negative, not since I've changed the theme of the website
