### ISSUE TITLE
Issue: Menu Donation Bar

### ISSUE THREAD

**Issue by LaocheXe** [septor/anteup#53]
When my team started using this plugin, the menu would display a bar on how much more this month's payments we would need. Now the bar no longer works - https://501stlegion-a3.com/   I will say nothing in the menu has been updated, for example, WS Skytten donated at the start of the website, yet the menu displays his name as Most recent donator(s), the same goes for CC Cruisie. Going to the donations page shows the recent donator(s) and sadly none of them are being displayed in the menu.

**Comment by Moc** [comment]
Are the more recent donations recorded in the database / admin area? Do you see donations coming in there?

**Comment by LaocheXe** [comment]
Yes, if you go to the Donations page that month's donation's show up with the users who donated. I even checked the database and it seems to be saving the information.

**Comment by Moc** [comment]
The quickest way to debug this is if I can access the database and your files (FTP). Would that be ok? If yes, could you send me some login info? moc@e107.org

I'll also try some manual testing when I get the time... Hopefully by the end of the week.

**Comment by LaocheXe** [comment]
Already sent, looks like the menu only shows the first few in the database.

**Comment by Moc** [comment]
1) I don't see anything wrong with the progress bar. 

Your goal is set to 200 
In between the period of november 2nd (last due) and december 1st (due) you have received 215. 
So the progress bar is full (over 100% actually). 

If I manually change the variables, the progress bar responds like it should. 


2) The list of most recent donators seems to be wrong indeed. I'll check this out further now.

**Comment by Moc** [comment]
I have fixed the most recent donators, it was ordered the wrong way around (e.g. the first donators first, not the last). 

I have pushed the bugfix on your website already. The fix will also be included in the next release of AnteUp.

**Comment by Moc** [comment]
@septor I think it's time to release a new update. There have been 30 commits since the last release and I think users may start to experience issues which are already fixed in the repo.

**Comment by Moc** [comment]
@LaocheXe can you confirm that the issue(s) is/are fixed on your website?

**Comment by LaocheXe** [comment]
This is fixed
