### ISSUE TITLE
Q/I: Shortcode Parameter Null

### ISSUE THREAD

**Issue by LaocheXe** [septor/anteup#54]
Using the new e107 debugger on Chrome - I notice at the bottom this warning message:

Warning in_array() expects parameter 2 to be array, null given, Line 103 of /usr/www/xxxxxxxx/501st/e107/e107_plugins/anteup/anteup_shortcodes.php

**Comment by septor** [comment]
`anteup_shortcodes.php` is no longer used and can be deleted.

**Comment by Moc** [comment]
This needs some clarification. In the newest update (not released yet), the shortcodes are made available globally. In the latest release this is not done yet and the anteup_shortcodes.php file is still in use. 

Anyway, the issue can be closed as I think it is not present in the global shortcodes file in the latest release.
