### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by leeb1981** [septor/anteup#57]
Create donations currency selection not working
![Screenshot_20231002_174906_Chrome](https://github.com/septor/anteup/assets/18101772/6656ce0b-c0a0-4830-b4c7-f60c238d8c46)

Donations tracker not updating when a donation is made. Dates etc not showing.

![Screenshot_20231002_180058_Chrome](https://github.com/septor/anteup/assets/18101772/8fcd103a-e098-4903-bb09-ff359aa0ccf2)

Transaction id  when donation made didn't match to the transaction id showed on PayPal

The donate page is still working as it should . Maybe the option of creating a monthly donation might be a good option to add so they can choose from a 1 time or monthly subscription donation.

**Comment by Moc** [comment]
Thank you. For a next time, please separate each bug report or feature request into separate issues on Github. 

1. Currency selector not working
I just pushed a code-cleanup commit which includes PHP8 compatibility fixes. This should also solve the currency selector issue. 

2. Donation tracker issue.
Looking into it. Not fixed yet. 

3. Transaction ID in Admin Area does not match transaction ID in PayPal. 
Not confirmed yet. Still have to test. 

4. Option to create recurring donations
This is a new feature request. Please post it up as a new github issue.

**Comment by Moc** [comment]
With all the latest changes, I assume the four issues have either been fixed or have been posted as a new separate issue. So I am closing this issue.
